# Generated by Django 3.1.1 on 2022-06-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
