# Generated by Django 3.1.1 on 2022-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20220608_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
    ]
