# Generated by Django 3.1.1 on 2022-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20220609_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='Tickets',
        ),
    ]
